# Generated by Django 3.0.2 on 2020-02-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_phonebody_phonecamera_phoneextras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='itembrand',
            options={'verbose_name': 'Item Brand', 'verbose_name_plural': 'Item Brands'},
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name': 'Item Category', 'verbose_name_plural': 'Item Categories'},
        ),
        migrations.AlterModelOptions(
            name='itemmodel',
            options={'verbose_name': 'Item Model', 'verbose_name_plural': 'Item Models'},
        ),
        migrations.AlterModelOptions(
            name='phonebody',
            options={'verbose_name': 'Phone Body', 'verbose_name_plural': 'Phone Bodies'},
        ),
        migrations.AlterModelOptions(
            name='phonecamera',
            options={'verbose_name': 'Phone Camera', 'verbose_name_plural': 'Phone Cameras'},
        ),
        migrations.AlterModelOptions(
            name='phonedisplayspec',
            options={'verbose_name': 'Phone Display Spec', 'verbose_name_plural': 'Phone Display Specs'},
        ),
        migrations.AlterModelOptions(
            name='phoneextras',
            options={'verbose_name': 'Phone Extra', 'verbose_name_plural': 'Phone Extras'},
        ),
        migrations.AlterModelOptions(
            name='phonefeature',
            options={'verbose_name': 'Phone Feature', 'verbose_name_plural': 'Phone Features'},
        ),
        migrations.AlterModelOptions(
            name='phonestechnicalspec',
            options={'verbose_name': 'Phone Technical Spec', 'verbose_name_plural': 'Phone Technical Specs'},
        ),
    ]
