# Generated by Django 3.0.2 on 2020-02-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='ddd', max_length=255),
            preserve_default=False,
        ),
    ]
